#!/bin/sh
. "/etc/pkg.conf"
if [ -z "$1" ]; then
    printf 'Specify package to remove.\n'
    exit 1
fi
package="$1"
pkgfile="$REPO/$package.pkg"
if ! [ -f "$pkgfile" ]; then
    printf "##### %s doesn't exist ######\n" "$package"
    exit 1
fi
. "$pkgfile" || exit 1
if ! [ -f "$DB/$package-$version.tar.xz" ]; then
    printf "##### %s install tarball doesn't exist ######\n" "$package"
    exit 1
fi
tar tf "$DB/$package-$version.tar.xz" |
while read -r file; do
    rm -dv "$file"
done
