#!/bin/sh
. "/etc/pkg.conf"

if [ -z "$1" ]; then
    printf 'You have to specify which package to install\n'
    exit 1
fi

extract() {
    case $1 in
        *.tar|*.xz|*.txz|*.gz)
            cd "$2" || exit 1
            tar xvf "$1" --strip-components=1 || exit 1
            ;;
        *.zip)
            cd "$2" || exit 1
            unzip "$1" || exit 1
            ;;
        *)
            cp -f "$1" "$2"
            ;;
    esac
}

install_pkg() {
    printf "##### Installing #####\n"
    tar xvf "$DB/$package-$version.tar.xz" -C /
}

package="$1"
pkgfile="$(find "$REPO" -mindepth 1 -maxdepth 2 -type d -wholename "*$package")/Pkgfile"
if [ "$(echo "$pkgfile" | wc -l)" -gt '1' ]; then
    printf "%s\n" "$pkgfile" | while read -r pkgfile; do
        . "$pkgfile"
        category="$(realpath --relative-to="$REPO" "$pkgfile" | cut -d/ -f1)"
        printf "%s/%s: %s\n" "$category" "$name" "$desc"
        unset category name desc
    done
    printf "Specify which program to install"
    exit 1
fi
if ! [ -f "$pkgfile" ]; then
    printf "##### %s not found ######\n" "$package"
    exit 1
fi
. "$pkgfile" || exit 1

export MAKEFLAGS
[ -d "$CACHE" ] || mkdir -p "$CACHE"
[ -d "$DB" ] || mkdir -p "$DB"
trap 'rm -rf $PROC' HUP INT QUIT TERM PWR EXIT
PROC="$(mktemp -d /tmp/pkg.XXXXXXXX)"
SOURCES="$PROC/sources"
BUILD="$PROC/build"
INSTALL="$PROC/install"
mkdir -p \
    "$SOURCES" \
    "$BUILD" \
    "$INSTALL"

for depend in $depends; do
    "$0" "$depend" || exit 1
done || exit 1

if [ -f "$DB/$package-$version.tar.xz" ]; then
    printf "##### %s already built, only installing #####\n" "$package"
    install_pkg
    exit 0
fi

echo "$sources" | tr ' ' '\n' | while IFS= read -r url; do
    file="$(echo "$url" | sed 's_.*/__g')"
    printf "##### Downloading '%s' ######\n" "$file"
    if command -v wget >/dev/null; then
        wget -c --directory-prefix="$CACHE/$package/" "$url"
    else
        if command -v curl >/dev/null; then
            curl -C - --output-dir "$CACHE/$package/" -O "$url"
        else
            printf 'No download command was able to be found, exiting\n'
            exit 1
        fi
    fi
done

printf "##### Copying sources #####\n"
cp -fv "$CACHE/$package"/* "$SOURCES"
cp -fv -- "$(dirname "$pkgfile")/files"/* "$SOURCES"

printf "##### Extracting sources #####\n"
for file in "$SOURCES"/*; do
    extract "$file" "$BUILD" || exit 1
done

printf "##### Building package #####\n"
cd "$BUILD" || exit 1
build || exit 1
printf "##### Adding install files to tarball #####\n"
cd "$INSTALL" || exit 1
tar cafv "$DB/$package-$version.tar.xz" ./*
install_pkg
