#!/bin/sh
set -x
. "/etc/pkg.conf"

if [ -z "$1" ]; then
    printf 'You have to specify which package to install\n'
    exit 1
fi

extract() {
    case $1 in
        *.tar|*.xz|*.txz|*.gz)
            cd "$2" || exit 1
            tar xvf "$1" --strip-components=1
            ;;
        *)
            cp -f "$1" "$2"
            ;;
    esac
}

install_pkg() {
    printf "##### Installing #####\n"
    tar xvf "$DB/$package-$version.tar.xz" -C /
}

package="$1"
pkgfile="$(find "$REPO" -maxdepth 0 -mindepth 0 -type d -name "$package")/Pkgfile"
if ! [ -f "$pkgfile" ]; then
    printf "##### %s doesn't exist ######\n" "$package"
    exit 1
fi
. "$pkgfile" || exit 1

export MAKEFLAGS
[ -d "$CACHE" ] || mkdir -p "$CACHE"
[ -d "$DB" ] || mkdir -p "$DB"
trap 'rm -rf $PROC' HUP INT QUIT TERM PWR EXIT
PROC="$(mktemp -d /tmp/pkg.XXXXXXXX)"
SOURCES="$PROC/sources"
BUILD="$PROC/build"
INSTALL="$PROC/install"
mkdir -p \
    "$SOURCES" \
    "$BUILD" \
    "$INSTALL"

for depend in $depends; do
    if ! [ -f "$REPO/$depend.pkg" ]; then
        printf "##### %s doesn't exist ######\n" "$depend"
        exit 1
    fi
    "$0" "$depend" || exit 1
done

if [ -f "$DB/$package-$version.tar.xz" ]; then
    printf "##### %s already built, only installing #####\n" "$package"
    install_pkg
    exit 0
fi

echo "$sources" | tr ' ' '\n' | while IFS= read -r url; do
    file="$(echo "$url" | sed 's_.*/__g')"
    printf "##### Downloading '%s' ######\n" "$file"
    if command -v wget >/dev/null; then
        wget -c --directory-prefix="$CACHE/$package/" "$url"
    else
        if command -v curl >/dev/null; then
            curl -C - --output-dir "$CACHE/$package/" -O "$url"
        else
            printf 'No download command was able to be found, exiting\n'
            exit 1
        fi
    fi
done

printf "##### Copying sources #####\n"
cp -rfv "$CACHE/$package"/* "$SOURCES"

printf "##### Extracting sources #####\n"
for file in "$SOURCES"/*; do
    extract "$file" "$BUILD" || exit 1
done

printf "##### Building package #####\n"
cd "$BUILD" || exit 1
build || exit 1
printf "##### Adding install files to tarball #####\n"
cd "$INSTALL" || exit 1
tar cafv "$DB/$package-$version.tar.xz" ./*
install_pkg
