#!/bin/sh
PACKAGE="$1"
if [ -z "$PACKAGE" ]; then
    printf "ERROR: Specify package to install\n"
    exit 1
fi
. "$HOME/.local/src/pkg/pkg.conf"
PROC="$(mktemp -d /tmp/pkg.XXXXXX)"
INSTALL="$PROC/install"
BUILD="$PROC/build"
mkdir -p "$CACHE/$PACKAGE" "$INSTALL" "$BUILD"
pkgfile="$(find $REPOS -type f -name "*.pkg" | sed 1q | grep "$PACKAGE")"
. "$pkgfile"
cd "$CACHE/$PACKAGE"
printf 'Downloading files\n'
echo "$sources" | tr ' ' '\n' | while IFS= read -r URL; do
    FILE="$(echo "$URL" | sed 's_.*/__g')"
    printf "Downloading '%s'.\n" "$FILE"
    test -f "$CACHE/$PACKAGE/$FILE" ||
    curl -L -C - -f -o "$CACHE/$PACKAGE/$FILE" "$URL"
done
printf 'Starting build\n'
build
cd "$INSTALL"
find -type f > "$CACHE/$PACKAGE/file.list"
printf 'Installing files\n'
doas cp -rfv ./* /
rm -rf "$PROC"
